name: Build and Test

on:
  push:
    branches: [ master, trying, staging ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: ['chrome', 'firefox']

    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npx web-ext lint
    - run: SELENIUM_BROWSER=${{ matrix.browser }} npm test
    - uses: ouzi-dev/commit-status-updater@v1.1.0
      with:
        name: "build"
