name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: ['chrome', 'firefox']

    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npx web-ext lint
    - run: SELENIUM_BROWSER=${{ matrix.browser }} npm test
